---
# defaults file for filebeat
app_name: filebeat
image_name: registry:5000/filebeat
version: 7.4.1
root: /opt/filebeat
log_dir: "{{ root }}/log"
log_sign: filebeat
log_sign2: filebeat
log_files: []
directories:
  - "{{root}}/config"
  - "{{root}}/log"
  - "{{root}}/log/{{log_sign}}"

template_files:
  - filebeat.yml



