{
 "title": "API-COST",
 "description": "API调用耗时监控",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "API 响应耗时",
   "type": "graph",
   "description": "api",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(server_monitor_api_cmd_cost{cmd!=\"CREATE_ACCOUNT\"}) by (cmd)",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "CREATE_ACCOUNT 响应耗时",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(server_monitor_api_cmd_cost{cmd=\"CREATE_ACCOUNT\"}) by (cmd)"
    }
   ]
  },
  {
   "title": "event cost",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(server_monitor_event_method_cost) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}