{
 "title": "api-monitor",
 "description": "api调用统计11",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "query": "5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "每秒api调用500错误数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(server_monitor_api_cmd_stats{code=\"500\"}[5m])",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "每秒事件报错数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(server_monitor_event_method_stats{type='error'}[5m]) ",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "每秒api调用",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(server_monitor_api_cmd_stats[$interval]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(rate(server_monitor_api_cmd_stats{code!=\"0\"}[$interval]))",
     "legendFormat": "unsuccessful"
    }
   ]
  }
 ]
}