---
# tasks file for javaprogram

- name: pull  image
  docker_image:
    name: "{{ image_name }}"
    tag: "{{ version }}"
    force: yes
    state: present
  become: yes


- name: Create directories
  file:
    name: "{{ item }}"
    state: directory
  become: yes
  with_items: '{{ directories }}'
  when: directories is defined

- name: copy template files
  template:
    src: "{{ item|safe }}.j2"
    dest: '{{ root }}/{{ version }}/config/{{ item|safe }}'
  become: yes
  with_items: '{{ template_files }}'
  when: template_files is defined

- name: copy files
  copy:
    src: "{{ item|safe }}"
    dest: '{{ root }}/{{ version }}/{{ item|safe }}'
  become: yes
  with_items: '{{ copy_files }}'
  when: copy_files is defined

- name: Start container
  docker_container:
    name: "{{ app_name }}"
    image: "{{ image_name }}:{{ version }}"
    working_dir: /workspace
    volumes:
      - '{{ root }}/{{ version }}/config:/workspace/config'
      - '{{ root }}/log:/workspace/log'
    network_mode: host
    restart_policy: always
    recreate: yes
    log_driver: json-file
    # stop_timeout: 1800
    log_options:
      max-size: 100m
      max-file: "2"
  become: yes