---
# tasks file for rabbitmq
- name: pull  image
  docker_image:
    name: "{{ image_name }}"
    tag: "{{ version }}"
    force_source: yes
    state: present
  become: yes


- name: Create directories
  file:
    name: "{{ item }}"
    state: directory
    owner: 100
    group: 1000
  become: yes
  with_items: '{{ directories }}'
  when: directories is defined

- name: copy template files
  template:
    src: "{{ item|safe }}.j2"
    dest: '{{ root }}/config/{{ item|safe }}'
  become: yes
  with_items: '{{ template_files }}'
  when: template_files is defined

- name: copy files
  copy:
    src: "{{ item|safe }}"
    dest: '{{ root }}/{{ item|safe }}'
  become: yes
  with_items: '{{ copy_files }}'
  when: copy_files is defined



- name: Start container
  docker_container:
    name: "{{ app_name }}"
    image: "{{ image_name }}:{{ version }}"
    # volumes:
    #   - '{{ root }}/data:/consul/data'
    #   - '{{ root }}/config:/consul/config'
    #   - '{{ root }}/log:/consul/log'
    # network_mode: host
    ports:
      - "5672:5672"
    restart_policy: always
    state: started
    log_driver: json-file
    log_options:
      max-size: 100m
      max-file: "2"
  become: yes