---
# tasks file for repository
- name: pull registry image
  docker_image:
    name: "{{ image_name }}"
    tag: "{{ version }}"
    force: yes
    state: present
  become: yes

- name: Start registry container
  docker_container:
    name: registry
    image: "{{ image_name }}:{{ version }}"
    volumes:
      - '{{ root }}:/var/lib/registry'
    ports:
      - "5000:5000"
    # network_mode: host
    restart_policy: always
    recreate: yes
    log_driver: json-file
    log_options:
      max-size: 10m
      max-file: "2"
  become: yes
