---
# defaults file for redis
redis_name: redis-3.2.10.tar.gz
redis_file: redis-3.2.10
redis_root: "/opt/{{redis_file}}"

app_name: redis
image_name: registry:5000/redis
version: 3.2.10
root: /opt/redis

directories:
  - "{{root}}/lib"
  - "{{root}}/config"
  - "{{root}}/log"

template_files:
  - redis.conf