# Set hostname for other hosts
---

- hosts: all
  tasks:
  - blockinfile:
      name: /etc/hosts
      block: |
        {% for host in groups['all'] %}
        {{ hostvars[host].ansible_default_ipv4.address }}	{{ host }}
        {% endfor %}
    become: true