---
# defaults file for consul

app_name: consul
image_name: registry:5000/consul
version: latest
root: /opt/consul

directories:
  - "{{root}}/config"
  - "{{root}}/data"
  - "{{root}}/log"

template_files:
  - consul.hcl